In [1]:
import pandas as pd
raw = pd.read_csv('Bitcoin_tweets.csv')

C:\Users\yhwen\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (1,2,3,5,6,7,8,9,10,11,12) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [2]:
raw

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,is_retweet
0,DeSota Wilson,"Atlanta, GA","Biz Consultant, real estate, fintech, startups...",2009-04-26 20:05:09,8534.0,7605,4838,False,2021-02-10 23:59:04,Blue Ridge Bank shares halted by NYSE after #b...,['bitcoin'],Twitter Web App,False
1,CryptoND,NaN,üòé BITCOINLIVE is a Dutch platform aimed at inf...,2019-10-17 20:12:10,6769.0,1532,25483,False,2021-02-10 23:58:48,"üòé Today, that's this #Thursday, we will do a ""...","['Thursday', 'Btc', 'wallet', 'security']",Twitter for Android,False
2,Tdlmatias,"London, England","IM Academy : The best #forex, #SelfEducation, ...",2014-11-10 10:50:37,128.0,332,924,False,2021-02-10 23:54:48,"Guys evening, I have read this article about B...",NaN,Twitter Web App,False
3,Crypto is the future,NaN,I will post a lot of buying signals for BTC tr...,2019-09-28 16:48:12,625.0,129,14,False,2021-02-10 23:54:33,$BTC A big chance in a billion! Price: \487264...,"['Bitcoin', 'FX', 'BTC', 'crypto']",dlvr.it,False
4,Alex Kirchmaier üá¶üáπüá∏üá™ #FactsSuperspreader,Europa,Co-founder @RENJERJerky | Forbes 30Under30 | I...,2016-02-03 13:15:55,1249.0,1472,10482,False,2021-02-10 23:54:06,This network is secured by 9 508 nodes as of t...,['BTC'],Twitter Web App,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2558009,Ali,NaN,@TsukiverseToken will be releasing game on And...,2021-04-15 17:25:34,12.0,51,1227,False,2021-11-25 19:12:31,@Tsuga007 @AltCryptoGems Something Big is on t...,"['Tsuga', 'PlaytoEarn', 'game', 'ùôèùôéùôêùôÇùòº', 'BNB'...",Twitter for Android,False
2558010,hossin kh,NaN,NaN,2018-11-08 22:59:01,5.0,15,655,False,2021-11-25 19:12:28,@Tsuga007 @AltCryptoGems Something Big is on t...,"['Tsuga', 'PlaytoEarn', 'game', 'ùôèùôéùôêùôÇùòº', 'BNB'...",Twitter Web App,False
2558011,TRENDsMarket,NaN,Information and Comments Found Here Are Not In...,2021-08-18 23:10:11,64.0,0,0,False,2021-11-25 19:12:27,MATIC__ CRYPTO PRƒ∞CE Wƒ∞LL Rƒ∞SE_|__ #USD...,"['USDEGP', 'CNHTRY', 'USDHUF', 'GBPCHF', 'SAR'...",Twitter Web App,False
2558012,Ali,NaN,@TsukiverseToken will be releasing game on And...,2021-04-15 17:25:34,12.0,51,1227,False,2021-11-25 19:12:24,@Tsuga007 @AltCryptoGems Something Big is on t...,"['Tsuga', 'PlaytoEarn', 'game', 'ùôèùôéùôêùôÇùòº', 'BNB'...",Twitter for Android,False
2558013,Ali,NaN,@TsukiverseToken will be releasing game on And...,2021-04-15 17:25:34,12.0,51,1227,False,2021-11-25 19:12:18,@Tsuga007 @AltCryptoGems Something Big is on t...,"['Tsuga', 'PlaytoEarn', 'game', 'ùôèùôéùôêùôÇùòº', 'BNB'...",Twitter for Android,False

In [3]:
tweets = raw[['date','text','']]

In [4]:
tweets['date'] = pd.Series([str(item).split()[0] for item in tweets['date']])

C:\Users\yhwen\AppData\Local\Temp/ipykernel_15592/4119300719.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['date'] = pd.Series([str(item).split()[0] for item in tweets['date']])

In [4]:
tweets.head()

         date                                               text
0  2021-02-10  Blue Ridge Bank shares halted by NYSE after #b...
1  2021-02-10  üòé Today, that's this #Thursday, we will do a "...
2  2021-02-10  Guys evening, I have read this article about B...
3  2021-02-10  $BTC A big chance in a billion! Price: \487264...
4  2021-02-10  This network is secured by 9 508 nodes as of t...

In [5]:
from string import punctuation
def remove_punctuation_digit(document):
    document = document.lower()
    no_punct = ''.join([character for character in document if character not in punctuation])
    no_digit = ''.join([character for character in no_punct if not character.isdigit()])
    return no_digit

In [6]:
tweets['text'] = pd.Series([str(item) for item in tweets['text']])

C:\Users\yhwen\AppData\Local\Temp/ipykernel_23968/751617327.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['text'] = pd.Series([str(item) for item in tweets['text']])

In [7]:
tweets['text'] = tweets['text'].apply(remove_punctuation_digit)

C:\Users\yhwen\AppData\Local\Temp/ipykernel_23968/4056150484.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['text'] = tweets['text'].apply(remove_punctuation_digit)

In [8]:
tweets

               date                                               text
0        2021-02-10  blue ridge bank shares halted by nyse after bi...
1        2021-02-10  üòé today thats this thursday we will do a üé¨ tak...
2        2021-02-10  guys evening i have read this article about bt...
3        2021-02-10  btc a big chance in a billion price    bitcoin...
4        2021-02-10  this network is secured by   nodes as of today...
...             ...                                                ...
2558009  2021-11-25  tsuga altcryptogems something big is on the wa...
2558010  2021-11-25  tsuga altcryptogems something big is on the wa...
2558011  2021-11-25  matic   crypto    priÃáce wiÃáll riÃáse   usdegp ...
2558012  2021-11-25  tsuga altcryptogems something big is on the wa...
2558013  2021-11-25  tsuga altcryptogems something big is on the wa...

[2558014 rows x 2 columns]

In [9]:
def remove_nonenglish(document):
    encoded_string = document.encode("ascii", "ignore")
    decode_string = encoded_string.decode()
    return decode_string

In [10]:
tweets['text'] = tweets['text'].apply(remove_nonenglish)

C:\Users\yhwen\AppData\Local\Temp/ipykernel_23968/1670950604.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['text'] = tweets['text'].apply(remove_nonenglish)

In [11]:
tweets

               date                                               text
0        2021-02-10  blue ridge bank shares halted by nyse after bi...
1        2021-02-10   today thats this thursday we will do a  take ...
2        2021-02-10  guys evening i have read this article about bt...
3        2021-02-10  btc a big chance in a billion price    bitcoin...
4        2021-02-10  this network is secured by   nodes as of today...
...             ...                                                ...
2558009  2021-11-25  tsuga altcryptogems something big is on the wa...
2558010  2021-11-25  tsuga altcryptogems something big is on the wa...
2558011  2021-11-25  matic   crypto    price will rise   usdegp   c...
2558012  2021-11-25  tsuga altcryptogems something big is on the wa...
2558013  2021-11-25  tsuga altcryptogems something big is on the wa...

[2558014 rows x 2 columns]

In [12]:
tweets = tweets.drop_duplicates(['text'])

In [13]:
tweets

               date                                               text
0        2021-02-10  blue ridge bank shares halted by nyse after bi...
1        2021-02-10   today thats this thursday we will do a  take ...
2        2021-02-10  guys evening i have read this article about bt...
3        2021-02-10  btc a big chance in a billion price    bitcoin...
4        2021-02-10  this network is secured by   nodes as of today...
...             ...                                                ...
2558005  2021-11-25               thx for playing btc httpstcohkuhqsjn
2558006  2021-11-25  goldseanft i really believe that this project ...
2558007  2021-11-25  peterhuntcrypto samuratoken\n gem for \n\n liq...
2558008  2021-11-25  opeoluwafalodun cryptojm aurofficial the aurum...
2558011  2021-11-25  matic   crypto    price will rise   usdegp   c...

[1731843 rows x 2 columns]

In [14]:
def remove_n(document):
    re_n = document.replace("\n", "") 
    return re_n 
tweets['text'] = tweets['text'].apply(remove_n)

C:\Users\yhwen\AppData\Local\Temp/ipykernel_23968/584922012.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['text'] = tweets['text'].apply(remove_n)

In [15]:
tweets

               date                                               text
0        2021-02-10  blue ridge bank shares halted by nyse after bi...
1        2021-02-10   today thats this thursday we will do a  take ...
2        2021-02-10  guys evening i have read this article about bt...
3        2021-02-10  btc a big chance in a billion price    bitcoin...
4        2021-02-10  this network is secured by   nodes as of today...
...             ...                                                ...
2558005  2021-11-25               thx for playing btc httpstcohkuhqsjn
2558006  2021-11-25  goldseanft i really believe that this project ...
2558007  2021-11-25  peterhuntcrypto samuratoken gem for  liquidity...
2558008  2021-11-25  opeoluwafalodun cryptojm aurofficial the aurum...
2558011  2021-11-25  matic   crypto    price will rise   usdegp   c...

[1731843 rows x 2 columns]

In [16]:
prices = pd.read_csv("BTC-USD.csv")

prices["Delta"] = prices["Close"] - prices["Open"]
dates = prices["Date"]
delta = prices["Delta"]
opens = prices["Open"]

sentiment = {}
for i in range(len(dates)):
    if abs(delta[i]) / opens[i] <= 0.01:
        sentiment[dates[i]] = "Neutral"
    else:
        if delta[i] > 0:
            sentiment[dates[i]] = "Positive"
        else:
            sentiment[dates[i]] = "Negative"

In [17]:
sentiment

{'2021-02-05': 'Positive',
 '2021-02-06': 'Positive',
 '2021-02-07': 'Neutral',
 '2021-02-08': 'Positive',
 '2021-02-09': 'Neutral',
 '2021-02-10': 'Negative',
 '2021-02-11': 'Positive',
 '2021-02-12': 'Neutral',
 '2021-02-13': 'Neutral',
 '2021-02-14': 'Positive',
 '2021-02-15': 'Negative',
 '2021-02-16': 'Positive',
 '2021-02-17': 'Positive',
 '2021-02-18': 'Neutral',
 '2021-02-19': 'Positive',
 '2021-02-20': 'Neutral',
 '2021-02-21': 'Positive',
 '2021-02-22': 'Negative',
 '2021-02-23': 'Negative',
 '2021-02-24': 'Positive',
 '2021-02-25': 'Negative',
 '2021-02-26': 'Negative',
 '2021-02-27': 'Neutral',
 '2021-02-28': 'Negative',
 '2021-03-01': 'Positive',
 '2021-03-02': 'Negative',
 '2021-03-03': 'Positive',
 '2021-03-04': 'Negative',
 '2021-03-05': 'Neutral',
 '2021-03-06': 'Neutral',
 '2021-03-07': 'Positive',
 '2021-03-08': 'Positive',
 '2021-03-09': 'Positive',
 '2021-03-10': 'Positive',
 '2021-03-11': 'Positive',
 '2021-03-12': 'Neutral',
 '2021-03-13': 'Positive',
 '2021-03-14': 'Negative',
 '2021-03-15': 'Negative',
 '2021-03-16': 'Positive',
 '2021-03-17': 'Positive',
 '2021-03-18': 'Negative',
 '2021-03-19': 'Neutral',
 '2021-03-20': 'Neutral',
 '2021-03-21': 'Negative',
 '2021-03-22': 'Negative',
 '2021-03-23': 'Neutral',
 '2021-03-24': 'Negative',
 '2021-03-25': 'Negative',
 '2021-03-26': 'Positive',
 '2021-03-27': 'Positive',
 '2021-03-28': 'Neutral',
 '2021-03-29': 'Positive',
 '2021-03-30': 'Positive',
 '2021-03-31': 'Neutral',
 '2021-04-01': 'Neutral',
 '2021-04-02': 'Neutral',
 '2021-04-03': 'Negative',
 '2021-04-04': 'Positive',
 '2021-04-05': 'Neutral',
 '2021-04-06': 'Negative',
 '2021-04-07': 'Negative',
 '2021-04-08': 'Positive',
 '2021-04-09': 'Neutral',
 '2021-04-10': 'Positive',
 '2021-04-11': 'Neutral',
 '2021-04-12': 'Neutral',
 '2021-04-13': 'Positive',
 '2021-04-14': 'Neutral',
 '2021-04-15': 'Neutral',
 '2021-04-16': 'Negative',
 '2021-04-17': 'Negative',
 '2021-04-18': 'Negative',
 '2021-04-19': 'Neutral',
 '2021-04-20': 'Positive',
 '2021-04-21': 'Negative',
 '2021-04-22': 'Negative',
 '2021-04-23': 'Negative',
 '2021-04-24': 'Negative',
 '2021-04-25': 'Negative',
 '2021-04-26': 'Positive',
 '2021-04-27': 'Positive',
 '2021-04-28': 'Neutral',
 '2021-04-29': 'Negative',
 '2021-04-30': 'Positive',
 '2021-05-01': 'Neutral',
 '2021-05-02': 'Negative',
 '2021-05-03': 'Positive',
 '2021-05-04': 'Negative',
 '2021-05-05': 'Positive',
 '2021-05-06': 'Negative',
 '2021-05-07': 'Positive',
 '2021-05-08': 'Positive',
 '2021-05-09': 'Negative',
 '2021-05-10': 'Negative',
 '2021-05-11': 'Positive',
 '2021-05-12': 'Negative',
 '2021-05-13': 'Neutral',
 '2021-05-14': 'Neutral',
 '2021-05-15': 'Negative',
 '2021-05-16': 'Neutral',
 '2021-05-17': 'Negative',
 '2021-05-18': 'Negative',
 '2021-05-19': 'Negative',
 '2021-05-20': 'Positive',
 '2021-05-21': 'Negative',
 '2021-05-22': 'Neutral',
 '2021-05-23': 'Negative',
 '2021-05-24': 'Positive',
 '2021-05-25': 'Negative',
 '2021-05-26': 'Positive',
 '2021-05-27': 'Negative',
 '2021-05-28': 'Negative',
 '2021-05-29': 'Negative',
 '2021-05-30': 'Positive',
 '2021-05-31': 'Positive',
 '2021-06-01': 'Negative',
 '2021-06-02': 'Positive',
 '2021-06-03': 'Positive',
 '2021-06-04': 'Negative',
 '2021-06-05': 'Negative',
 '2021-06-06': 'Neutral',
 '2021-06-07': 'Negative',
 '2021-06-08': 'Neutral',
 '2021-06-09': 'Positive',
 '2021-06-10': 'Negative',
 '2021-06-11': 'Positive',
 '2021-06-12': 'Negative',
 '2021-06-13': 'Positive',
 '2021-06-14': 'Positive',
 '2021-06-15': 'Neutral',
 '2021-06-16': 'Negative',
 '2021-06-17': 'Neutral',
 '2021-06-18': 'Negative',
 '2021-06-19': 'Neutral',
 '2021-06-20': 'Neutral',
 '2021-06-21': 'Negative',
 '2021-06-22': 'Positive',
 '2021-06-23': 'Positive',
 '2021-06-24': 'Positive',
 '2021-06-25': 'Negative',
 '2021-06-26': 'Positive',
 '2021-06-27': 'Positive',
 '2021-06-28': 'Neutral',
 '2021-06-29': 'Positive',
 '2021-06-30': 'Negative',
 '2021-07-01': 'Negative',
 '2021-07-02': 'Positive',
 '2021-07-03': 'Positive',
 '2021-07-04': 'Positive',
 '2021-07-05': 'Negative',
 '2021-07-06': 'Positive',
 '2021-07-07': 'Negative',
 '2021-07-08': 'Negative',
 '2021-07-09': 'Positive',
 '2021-07-10': 'Neutral',
 '2021-07-11': 'Positive',
 '2021-07-12': 'Negative',
 '2021-07-13': 'Negative',
 '2021-07-14': 'Neutral',
 '2021-07-15': 'Negative',
 '2021-07-16': 'Negative',
 '2021-07-17': 'Neutral',
 '2021-07-18': 'Neutral',
 '2021-07-19': 'Negative',
 '2021-07-20': 'Negative',
 '2021-07-21': 'Positive',
 '2021-07-22': 'Neutral',
 '2021-07-23': 'Positive',
 '2021-07-24': 'Positive',
 '2021-07-25': 'Positive',
 '2021-07-26': 'Positive',
 '2021-07-27': 'Positive',
 '2021-07-28': 'Positive',
 '2021-07-29': 'Neutral',
 '2021-07-30': 'Positive',
 '2021-07-31': 'Negative',
 '2021-08-01': 'Negative',
 '2021-08-02': 'Negative',
 '2021-08-03': 'Negative',
 '2021-08-04': 'Positive',
 '2021-08-05': 'Positive',
 '2021-08-06': 'Positive',
 '2021-08-07': 'Positive',
 '2021-08-08': 'Negative',
 '2021-08-09': 'Positive',
 '2021-08-10': 'Negative',
 '2021-08-11': 'Neutral',
 '2021-08-12': 'Negative',
 '2021-08-13': 'Positive',
 '2021-08-14': 'Negative',
 '2021-08-15': 'Neutral',
 '2021-08-16': 'Negative',
 '2021-08-17': 'Negative',
 '2021-08-18': 'Neutral',
 '2021-08-19': 'Positive',
 '2021-08-20': 'Positive',
 '2021-08-21': 'Neutral',
 '2021-08-22': 'Neutral',
 '2021-08-23': 'Neutral',
 '2021-08-24': 'Negative',
 '2021-08-25': 'Positive',
 '2021-08-26': 'Negative',
 '2021-08-27': 'Positive',
 '2021-08-28': 'Neutral',
 '2021-08-29': 'Neutral',
 '2021-08-30': 'Negative',
 '2021-08-31': 'Neutral',
 '2021-09-01': 'Positive',
 '2021-09-02': 'Positive',
 '2021-09-03': 'Positive',
 '2021-09-04': 'Neutral',
 '2021-09-05': 'Positive',
 '2021-09-06': 'Positive',
 '2021-09-07': 'Negative',
 '2021-09-08': 'Negative',
 '2021-09-09': 'Positive',
 '2021-09-10': 'Negative',
 '2021-09-11': 'Neutral',
 '2021-09-12': 'Positive',
 '2021-09-13': 'Negative',
 '2021-09-14': 'Positive',
 '2021-09-15': 'Positive',
 '2021-09-16': 'Neutral',
 '2021-09-17': 'Negative',
 '2021-09-18': 'Positive',
 '2021-09-19': 'Negative',
 '2021-09-20': 'Negative',
 '2021-09-21': 'Negative',
 '2021-09-22': 'Positive',
 '2021-09-23': 'Positive',
 '2021-09-24': 'Negative',
 '2021-09-25': 'Neutral',
 '2021-09-26': 'Positive',
 '2021-09-27': 'Negative',
 '2021-09-28': 'Negative',
 '2021-09-29': 'Positive',
 '2021-09-30': 'Positive',
 '2021-10-01': 'Positive',
 '2021-10-02': 'Neutral',
 '2021-10-03': 'Positive',
 '2021-10-04': 'Positive',
 '2021-10-05': 'Positive',
 '2021-10-06': 'Positive',
 '2021-10-07': 'Negative',
 '2021-10-08': 'Neutral',
 '2021-10-09': 'Positive',
 '2021-10-10': 'Neutral',
 '2021-10-11': 'Positive',
 '2021-10-12': 'Negative',
 '2021-10-13': 'Positive',
 '2021-10-14': 'Neutral',
 '2021-10-15': 'Positive',
 '2021-10-16': 'Negative',
 '2021-10-17': 'Positive',
 '2021-10-18': 'Neutral',
 '2021-10-19': 'Positive',
 '2021-10-20': 'Positive',
 '2021-10-21': 'Negative',
 '2021-10-22': 'Negative',
 '2021-10-23': 'Positive',
 '2021-10-24': 'Neutral',
 '2021-10-25': 'Positive',
 '2021-10-26': 'Negative',
 '2021-10-27': 'Negative',
 '2021-10-28': 'Positive',
 '2021-10-29': 'Positive',
 '2021-10-30': 'Neutral',
 '2021-10-31': 'Neutral',
 '2021-11-01': 'Neutral',
 '2021-11-02': 'Positive',
 '2021-11-03': 'Neutral',
 '2021-11-04': 'Negative',
 '2021-11-05': 'Neutral',
 '2021-11-06': 'Neutral',
 '2021-11-07': 'Positive',
 '2021-11-08': 'Positive',
 '2021-11-09': 'Neutral',
 '2021-11-10': 'Negative',
 '2021-11-11': 'Neutral',
 '2021-11-12': 'Negative',
 '2021-11-13': 'Neutral',
 '2021-11-14': 'Positive',
 '2021-11-15': 'Negative',
 '2021-11-16': 'Negative',
 '2021-11-17': 'Neutral',
 '2021-11-18': 'Negative',
 '2021-11-19': 'Positive',
 '2021-11-20': 'Positive',
 '2021-11-21': 'Negative',
 '2021-11-22': 'Negative',
 '2021-11-23': 'Positive',
 '2021-11-24': 'Negative',
 '2021-11-25': 'Neutral',
 '2021-11-26': 'Negative'}

In [18]:
tweets = tweets.drop([1347699,64943,137068,1885528])

In [19]:
date_list = list(tweets["date"])
tweets["Tag"] = [sentiment[date] for date in date_list]

In [20]:
tweets

,date,text,Tag
0,2021-02-10,blue ridge bank shares halted by nyse after bi...,Negative
1,2021-02-10,today thats this thursday we will do a take ...,Negative
2,2021-02-10,guys evening i have read this article about bt...,Negative
3,2021-02-10,btc a big chance in a billion price bitcoin...,Negative
4,2021-02-10,this network is secured by nodes as of today...,Negative
...,...,...,...
2558005,2021-11-25,thx for playing btc httpstcohkuhqsjn,Neutral
2558006,2021-11-25,goldseanft i really believe that this project ...,Neutral
2558007,2021-11-25,peterhuntcrypto samuratoken gem for liquidity...,Neutral
2558008,2021-11-25,opeoluwafalodun cryptojm aurofficial the aurum...,Neutral
2558011,2021-11-25,matic crypto price will rise usdegp c...,Neutral

In [21]:
from sklearn.model_selection import train_test_split

tweets_train, tweets_test = train_test_split(tweets, test_size=0.3, random_state=88)
tweets_train.shape, tweets_test.shape

((1212287, 3), (519552, 3))

In [22]:
from nltk.tokenize import word_tokenize
import nltk

tweets_train['text'] = tweets_train['text'].apply(word_tokenize)
tweets_test['text'] = tweets_test['text'].apply(word_tokenize)

C:\Users\yhwen\AppData\Local\Temp/ipykernel_23968/1583425993.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets_train['text'] = tweets_train['text'].apply(word_tokenize)
C:\Users\yhwen\AppData\Local\Temp/ipykernel_23968/1583425993.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets_test['text'] = tweets_test['text'].apply(word_tokenize)

In [23]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

def remove_stopwords(document):
    words = [word for word in document if not word in stop_words]
    return words

In [24]:
tweets_train['text'] = tweets_train['text'].apply(remove_stopwords)
tweets_test['text'] = tweets_test['text'].apply(remove_stopwords)

C:\Users\yhwen\AppData\Local\Temp/ipykernel_23968/1856369903.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets_train['text'] = tweets_train['text'].apply(remove_stopwords)
C:\Users\yhwen\AppData\Local\Temp/ipykernel_23968/1856369903.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets_test['text'] = tweets_test['text'].apply(remove_stopwords)

In [25]:
from nltk.stem import PorterStemmer
porter = PorterStemmer()

def stemmer(document):
    stemmed_document = [porter.stem(word) for word in document]
    return stemmed_document

In [27]:
tweets_train['text'] = tweets_train['text'].apply(stemmer)
tweets_test['text'] = tweets_test['text'].apply(stemmer)

C:\Users\yhwen\AppData\Local\Temp/ipykernel_23968/3906397559.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets_train['text'] = tweets_train['text'].apply(stemmer)
C:\Users\yhwen\AppData\Local\Temp/ipykernel_23968/3906397559.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets_test['text'] = tweets_test['text'].apply(stemmer)

In [28]:
from nltk.tokenize.treebank import TreebankWordDetokenizer
from sklearn.feature_extraction.text import CountVectorizer

text_train = tweets_train['text'].apply(TreebankWordDetokenizer().detokenize)
countvec_train = CountVectorizer(min_df = 0.005)
sparse_dtm_train = countvec_train.fit_transform(text_train)

In [29]:
text_test = tweets_test['text'].apply(TreebankWordDetokenizer().detokenize)
sparse_dtm_test = countvec_train.transform(text_test)

In [30]:
dtm_train = pd.DataFrame(sparse_dtm_train.toarray(), columns=countvec_train.get_feature_names(),index=tweets_train.index)
dtm_test = pd.DataFrame(sparse_dtm_test.toarray(), columns=countvec_train.get_feature_names(),index=tweets_test.index)

In [31]:
dtm_train.sum().sort_values(ascending=False)

bitcoin              977140
btc                  558584
crypto               338046
cryptocurr           221869
project              191868
                      ...
dogearmi               6372
yet                    6294
easi                   6290
cryptocurrencynew      6214
websit                 6210
Length: 433, dtype: int64

In [33]:
dtm_train

,accept,account,achiev,ada,addr,address,adopt,affiliatemarket,airdrop,airdropdet,...,world,worth,would,xlm,xrp,year,yet,yieldfarm,your,youtub
298511,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1188474,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1076446,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
61438,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
759439,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100913,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
729145,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1497377,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1282837,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
425567,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [34]:
tweets

,date,text,Tag
0,2021-02-10,blue ridge bank shares halted by nyse after bi...,Negative
1,2021-02-10,today thats this thursday we will do a take ...,Negative
2,2021-02-10,guys evening i have read this article about bt...,Negative
3,2021-02-10,btc a big chance in a billion price bitcoin...,Negative
4,2021-02-10,this network is secured by nodes as of today...,Negative
...,...,...,...
2558005,2021-11-25,thx for playing btc httpstcohkuhqsjn,Neutral
2558006,2021-11-25,goldseanft i really believe that this project ...,Neutral
2558007,2021-11-25,peterhuntcrypto samuratoken gem for liquidity...,Neutral
2558008,2021-11-25,opeoluwafalodun cryptojm aurofficial the aurum...,Neutral
2558011,2021-11-25,matic crypto price will rise usdegp c...,Neutral

In [35]:
tweets_train

,date,text,Tag
298511,2021-07-04,"[bitcoin, gt, difficulti, adjust, satoshi, gre...",Positive
1188474,2021-08-26,"[bnb, go, next, weekbtc, xrp, trx, bnb]",Negative
1076446,2021-08-15,"[k, subscrib, youtub, make, video, checoin, th...",Neutral
61438,2021-04-08,"[bitcoin, btc, bull, season, still, far, peak,...",Positive
759439,2021-08-08,"[bitcoin, price, us, dollar, btc, usd, btcusd,...",Negative
...,...,...,...
100913,2021-04-19,"[larg, bitcoin, btc, transact, hash, ddbfcbafc...",Neutral
729145,2021-08-09,"[bitcoin, k, coincid, doubt, httpstcolzwzgu]",Positive
1497377,2021-10-29,"[differ, coin, portfolio, mani, got, shibarmi,...",Positive
1282837,2021-10-18,"[bitcoin, diamond, top, diamond, rever, httpst...",Neutral
425567,2021-07-22,"[coinmarketcap, great, excel, project, also, r...",Neutral